### PR TITLE
feat: Update README.md

### PR DESCRIPTION
**Pull request by seal-mis**

### CODE REVIEW

**Review by scherermichael — CHANGES_REQUESTED** [review]
Test

**Comment by seal-mis** [comment]
test

**Review by scherermichael — APPROVED** [review]

**Review by scherermichael — CHANGES_REQUESTED** [review]
test2

**Review by scherermichael — APPROVED** [review]

**Review by scherermichael — DISMISSED** [review]
test3

**Review by scherermichael — DISMISSED** [review]
test4

**Pull request merged**
